# Generated by Django 4.2.10 on 2024-03-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_address_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="store_custo_last_na_2e448d_idx",
            ),
        ),
    ]
